[workspace]
members = [
    "crates/erasable",
    "crates/ptr-union",
    "crates/rc-borrow",
    "crates/rc-box",
    "crates/slice-dst",
    "crates/slice-dst-macros",
]

exclude = [
    "crates/slice-dst-macros/impl"
]
