[package]
name = "ptr-union"
version = "1.0.0-dev"
edition = "2018"

authors = ["Christopher Durham (cad97) <cad97@cad97.com>"]
description = "Pointer union types the size of a pointer by storing the tag in the alignment bits."
repository = "https://github.com/CAD97/pointer-utils/tree/master/crates/ptr-union"
readme = "README.md"
keywords = ["thin","pointer","union","enum"]
categories = ["data-structures","no-std","rust-patterns"]
license = "MIT OR APACHE-2.0"

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
paste = "0.1.6"

[dependencies.erasable]
version = "1.0.0-dev"
path = "../erasable"

[features]
default = ["alloc"]
alloc = ["erasable/alloc"]

[build-dependencies]
autocfg = "1.0.0"
